; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[env:waveshare_esp32s3_a7670]
platform = espressif32@6.10.0
framework = arduino
board = esp32-s3-devkitc-1

; Configure Flash and PSRAM for the ESP32-S3R2
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 16MB
monitor_filters = default, time, log2file, colorize

upload_speed = 921600

; Ensure Serial Monitor works on the native USB port
build_flags = 
    ; -D ARDUINO_USB_CDC_ON_BOOT=1
    ; -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM

; Serial Monitor Baud Rate
monitor_speed = 115200

; Required Library for cellular & AT commands
lib_deps =
  	adafruit/Adafruit NeoPixel @ 1.15.5
    vshymanskyy/TinyGSM @ ^0.12.0			
